
version: '2.1'
services:
  ubuntu-scm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - build_fileserver=${BUILD_FILESERVER:-http://fileserver.local}
    image: home1oss/ci-ubuntu:16.04
