# docker-compose build
# export: docker save registry.docker.local/yrd-ubuntu:16.04 > ${HOME}/Desktop/yrd-ubuntu.tar
version: '2.1'
services:
  ubuntu-scm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - build_fileserver=${BUILD_FILESERVER:-http://fileserver.local}
    image: ${DOCKER_REGISTRY:-registry.docker.local}/ci-ubuntu:16.04
